### PR TITLE
Add APIError for exceeding the Brickset API limit.

### PR DESCRIPTION
**Pull request by BrianBatchelder**
While experimenting with your app, I encountered [Brickset's](https://brickset.com/article/52664/api-version-3-documentation) "API limit exceeded" error. I noticed it wasn't handled by the [APIError](https://github.com/leolelego/Brickie-iOS/blob/master/sources/model/APIs/APIHelpers.swift) class, so I added it. Hope you find this helpful.

### CODE REVIEW

**Comment by leolelego** [comment]
Hi @BrianBatchelder 
This is s great point, when your API is validated by Brickset as request this issue should not occur. 
But I will definilty merge this commit. Just working on some stuff on 1.5 I will regroup in the same build. 

PR really appreciated!

**Comment by BrianBatchelder** [comment]
Hi, @leolelego . Glad you find this useful.

What do you mean by "when your API is validated by Brickset"? Is there a validation process for new API keys?

**Comment by leolelego** [comment]
@BrianBatchelder Yes but you need to justify your app is made to be shipped (an AppStore link for exemple). Once they validate they stop the calls limit on your API key.

**Comment by BrianBatchelder** [comment]
Interesting. At the moment, I'm not planning on creating my own app. I'd prefer to help with yours.

**Pull request merged**
